### PR TITLE
Adding DFD file

### LINKED ISSUE #21: Missing DFD
Requirements:

- Adding a Data-flow diagram to display the flow of the web-application

### PR DESCRIPTION
**Pull request by RanyWh**
Adding Data-flow diagram to show the flow of the web-application and its features.

Features included :
1. Search
2. Signing up
3. Signing In
4. Feed
5. Sending Course Request
6. Add Course
7. Study Group
8. Review
9. Feed
10. Chat

fixes #21

### CODE REVIEW

**Review by Davidco94 — DISMISSED** [review]
LGTM!

**Comment by idan1356** [comment]
LGTM

**Review by idan1356 — APPROVED** [review]
LGTM

**Review by shirazyomtov — DISMISSED** [review]
LGTM

**Review by natifridman — COMMENTED** [review]
Looks good, some comments/questions:
- Can a guest user use the search?
- Maybe instead of `user business` and `user private` we can use something like `private account` or `private view`?
- I see here notifications, is this something that needs to be added to the ERD?

**Review by shacharlevy — APPROVED** [review]
LGTM!

**Review by shirazyomtov — APPROVED** [review]
All changes appear to have been made, LGTM

**Review by natifridman — APPROVED** [review]
LGTM

**Pull request merged**
