### PR TITLE
Add ERD.pdf file

### LINKED ISSUE #20: Missing ERD
The ERD which provides a visual starting point for database design is missing.

### PR DESCRIPTION
**Pull request by shacharlevy**
Add an ERD which provides a visual starting point for database design. 
fixes #20

### CODE REVIEW

**Review by Davidco94 — DISMISSED** [review]
LGTM!

**Review by idan1356 — DISMISSED** [review]
LGMT!

**Review by shirazyomtov — DISMISSED** [review]
LGTM

**Comment by galitf** [comment]
If you are using user_id as a pk in User, why aren't you using user_id in Post and instead using username?
In Chat why do you need the sender_username if you are holding the student_course_id?
There are some fields that the name are not that clear: business_id, private_id make the fields name be more meaningful.

**Comment by shacharlevy** [comment]
> If you are using user_id as a pk in User, why aren't you using user_id in Post and instead using username? In Chat why do you need the sender_username if you are holding the student_course_id? There are some fields that the name are not that clear: business_id, private_id make the fields name be more meaningful.

Hi, I will replace the username by the user_id.
Regarding the second comment, we are holding the  student_course_id property because it provides us information about the course, the teacher and the student. We needed the sender in order to know who wrote each message. Do you think it is prefered to hold the user type instead?
Regarding to  business_id and private_id, we thought it was right to distinguish between them since both are users.

**Comment by shacharlevy** [comment]
> > If you are using user_id as a pk in User, why aren't you using user_id in Post and instead using username? In Chat why do you need the sender_username if you are holding the student_course_id? There are some fields that the name are not that clear: business_id, private_id make the fields name be more meaningful.
> 
> Same for `start_post_id` in `Post`, is this going to be something like a comment to posts? something like a parent post?

Yes, because we found that a post and a comment are very similar, we decided to merge them and add a field that shows us the initial creator.

**Comment by shacharlevy** [comment]
> > If you are using user_id as a pk in User, why aren't you using user_id in Post and instead using username? In Chat why do you need the sender_username if you are holding the student_course_id? There are some fields that the name are not that clear: business_id, private_id make the fields name be more meaningful.
> 
> Same for `start_post_id` in `Post`, is this going to be something like a comment to posts? something like a parent post?

Yes, because we found that a post and a comment are very similar, we decided to merge them and add a field that shows us the initial creator.

**Comment by natifridman** [comment]
> Hi, I will replace the username by the user_id. Regarding the second comment, we are holding the student_course_id property because it provides us information about the course, the teacher and the student. We needed the sender in order to know who wrote each message. Do you think it is prefered to hold the user type instead? Regarding to business_id and private_id, we thought it was right to distinguish between them since both are users.

Maybe holding the chat type will simplify it? (group chat/private chat)

> Yes, because we found that a post and a comment are very similar, we decided to merge them and add a field that shows us the initial creator.

Maybe a different name will be more clear?

> business_id and private_id fields are user_id's in context of "business" account (i.e. teacher), and "private" account (i.e. student).
would something along the lines of business_user_id/ private_user_id or teacher_user_id/student_user_id be more clear?

I think ` teacher_user_id/student_user_id` would be more clear. Why do you need to store the teacher ID in `Review` if it's already in the course and you have the course ID?

**Comment by shacharlevy** [comment]
> > Hi, I will replace the username by the user_id. Regarding the second comment, we are holding the student_course_id property because it provides us information about the course, the teacher and the student. We needed the sender in order to know who wrote each message. Do you think it is prefered to hold the user type instead? Regarding to business_id and private_id, we thought it was right to distinguish between them since both are users.
> 
> Maybe holding the chat type will simplify it? (group chat/private chat)
> 
> > Yes, because we found that a post and a comment are very similar, we decided to merge them and add a field that shows us the initial creator.
> 
> Maybe a different name will be more clear?
> 
> > business_id and private_id fields are user_id's in context of "business" account (i.e. teacher), and "private" account (i.e. student).
> > would something along the lines of business_user_id/ private_user_id or teacher_user_id/student_user_id be more clear?
> 
> I think ` teacher_user_id/student_user_id` would be more clear. Why do you need to store the teacher ID in `Review` if it's already in the course and you have the course ID?

1. If we'll add the chat type, we will still need the group_id to know which group the chat is associated with and the student_course_id to know between which teacher and which student the conversation is taking place (one of them will always be null).
2. Is initial_post_creator clear enough?
3. Ok. I will change it to  ` teacher_user_id/student_user_id`, and we don't need the teacher ID it will be fixed.

**Review by shirazyomtov — APPROVED** [review]
All changes appear to have been made, looking good to me

**Review by Yardengz — DISMISSED** [review]

**Comment by natifridman** [comment]
> 2. Is initial_post_creator clear enough?

What about something like `parent_post_id`?

Also, please use these [keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) to link the PR to the issue

**Review by shirazyomtov — APPROVED** [review]
LGTM

**Review by Yardengz — APPROVED** [review]

**Review by natifridman — APPROVED** [review]
LGTM, nice work! please remember to update the ERD if there will be changes later.
Could you please squash the commits?

**Comment by shacharlevy** [comment]
> LGTM, nice work! please remember to update the ERD if there will be changes later. Could you please squash the commits?

I squashed the commits :)

**Review by idan1356 — APPROVED** [review]
LGTM!

**Review by natifridman — APPROVED** [review]

**Review by shirazyomtov — APPROVED** [review]
LGTM

**Pull request merged**
