### PR TITLE
Renaming some models, fields and files

### PR DESCRIPTION
**Pull request by RanyWh**
**Duplicate of #69**, that was reverted since there was a conflict with the merged PR before it.
Made the necessary changes to resolve the conflict in the feed app #38.

### CODE REVIEW

**Review by idan1356 — DISMISSED** [review]
LGTM

**Review by shirazyomtov — APPROVED** [review]
LGTM

**Comment by galitf** [comment]
LGTM

**Review by natifridman — COMMENTED** [review]
Please resolve conflicts

**Comment by natifridman** [comment]
Any dependencies between this PR and #74?

**Review by natifridman — APPROVED** [review]
LGTM

**Review by natifridman — APPROVED** [review]
LGTM

**Review by shirazyomtov — APPROVED** [review]
LGTM

**Comment by Omeramsc** [comment]
Why is there a "duplicate" label for this PR?

**Comment by Omeramsc** [comment]
@RanyWh It does not imply dependency, but usually it means there's another PR that does the same thing, maybe making this one redundant.

**Pull request merged**
