### PR TITLE
Adding a Django development environment to the VM

### LINKED ISSUE #8: Creating a Django development environment
**Requirements:** 

1. Install and setup Pipenv for our project.
2. Installing Django and bootstrapping a Django website.

### PR DESCRIPTION
**Pull request by RanyWh**
- Setup Pipenv to install and manage Django and other Python dependencies
- Bootstrapped an empty Django application

**Steps to running the application:**

-"vagrant up"
-"vagrant ssh"
(inside the VM)
-"cd /vagrant"
-"pipenv run python manage.py runserver 0.0.0.0:8000"

The application can be accessed at:
> http://127.0.0.1:8000/

**Note:** ALL changes had been auto-generated

fixes #8

### CODE REVIEW

**Review by shirazyomtov — APPROVED** [review]
Looks good to me. 
I approve

**Review by natifridman — APPROVED** [review]
LGTM

**Review by shacharlevy — APPROVED** [review]
LGTM

**Review by Davidco94 — APPROVED** [review]
LGTM

**Pull request merged**
