### PR TITLE
Update ERD

### LINKED ISSUE #36: Update of ERD is needed
1. The type of date_time field in Chat is incorrect.
2. Each record in Chat table represents a message therefore the name Chat  should be replaced by Message.

### PR DESCRIPTION
**Pull request by shacharlevy**
- Replace the date_time field type in Chat from varchar to date.
- Replace Chat by Message (each record in the table represents a message).

fixes #36

### CODE REVIEW

**Review by shirazyomtov — DISMISSED** [review]
LGTM

**Review by idan1356 — APPROVED** [review]
LGTM

**Comment by Omeramsc** [comment]
Please add the ERD as an image file too, so it'll be visible from the repository without the need to clone it.

**Comment by shacharlevy** [comment]
> Need to add a couple of changes.
> 
> **Teacher_Course table :**
> 
> * Change experience field name to years of experience
> * Add a difficulty level field (enum)
> 
> **User :**
> 
> * Change phone_number field from int to char

Added :)

**Comment by shacharlevy** [comment]
> Please add the ERD as an image file too, so it'll be visible from the repository without the need to clone it.

Done :)

**Review by shirazyomtov — DISMISSED** [review]
LGTM

**Review by idan1356 — CHANGES_REQUESTED** [review]
Can you also change `group_description` in `Study_Group` to `textfield`?

**Comment by shacharlevy** [comment]
> Can you also change `group_description` in `Study_Group` to `textfield`?

Done

**Review by shirazyomtov — DISMISSED** [review]
LGTM

**Review by natifridman — DISMISSED** [review]
LGTM, please squash the commits

**Review by idan1356 — APPROVED** [review]
LGTM

**Comment by shacharlevy** [comment]
> LGTM, please squash the commits

Done

**Review by shirazyomtov — APPROVED** [review]
LGTM

**Review by idan1356 — APPROVED** [review]
LGTM

**Review by Davidco94 — APPROVED** [review]
LGTM!

**Review by natifridman — APPROVED** [review]

**Pull request merged**
